GET http://localhost:3000/orders?account_id=1234

###
GET http://localhost:3000/orders/652ac04b8c9954192aa01c78

###
POST http://localhost:3000/orders
Content-Type: application/json

{
  "account_id": "1234",
  "asset_id": "xpto11",
  "quantity": 100
}